[tool.poetry]
name = "stockexperts"
version = "0.1.0"
description = "stockexperts using crewAI"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<=3.13"
crewai = { extras = ["tools"], version = ">=0.70.1,<1.0.0" }
streamlit = "^1.39.0"
dash = "^2.18.2"


[tool.poetry.scripts]
stockexperts = "main:run"
run_crew = "main:run"
train = "main:train"
replay = "main:replay"
test = "main:test"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
